stages:
  - deploy
deploy-packshop-api:
  stage: deploy
  environment: prod
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install rsync openssh-client zip unzip -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n \tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # - 'echo -e "Host * \n Port 2222 \n  " >> ~/.ssh/config'
    - which rsync || ( apt-get update -y && apt-get install rsync -y )

  script:
    - echo "Deploying ${CI_COMMIT_SHA} from ${CI_COMMIT_REF_NAME} to test server"
    - ssh -v "$USERNAME"@"$HOST"
    - rsync -avz --no-perms --no-owner --no-group  --delete * "$USERNAME"@"$HOST":/var/www/packshop/api
    - ssh "$USERNAME"@"$HOST" "cd /var/www/packshop/api && chmod 777 deploy.sh && ./deploy.sh && echo "Script Running successfully""
  only:
    - main
  when: always
